
development:
  adapter: postgresql
  host: localhost
  port: 5432
  database: postgres 
  username: postgres
  password: gangstaz

test:  
  adapter: postgresql
  encoding: unicode
  database: testdb_pow
  pool: 5
  username: parseb
  password:	gangstaz